<template>
  <div class="flex justify-evenly text-xs my-[4.7mm]">
    <div class="flex flex-col items-center text-belstarRed justify-center">
      <h3>帳單消費分期</h3>
      <img
        src="../assets/img/address-barcode.png"
        alt="Barcode generated by Cognex Corporation"
        width="55"
      />
    </div>
    <div class="flex flex-col items-center text-belstarRed justify-center">
      <h3>網路/ATM預借現金</h3>
      <img
        src="../assets/img/address-barcode.png"
        alt="Barcode generated by Cognex Corporation"
        width="55"
      />
    </div>
  </div>
</template>
